function [C1,C2] = ParTransCropImg(Direct, Name1, Name2, TFORM1, TFORM2, AddCrop, B1, B2, D1, D2, Lambda1, Lambda2, i)
%% Transforms a single image pair denoted by Name1 and Name2 using the tforms
%  TFORM1 and TFORM2 (which were found using PreRun).  Cs denotes the
%  corners of the grid, and AddCrop is a vector that crops the image

        % Load and Transform Image 1
        Im1=double(imread(Name1) );
        Im2=double(imread(Name2) );     
        I1=imtransform( Im1,... %-B2) ,...
                TFORM1,...
                'nearest',...
                'FillValues', 0,...
                'XData', [AddCrop(1) AddCrop(2)],...
                'YData', [AddCrop(3) AddCrop(4)]) ;
         
        % Load and Transform Image 1
        I2=imtransform( Im2,... %-B2) ,...
                TFORM2,...
                'nearest',...
                'FillValues', 0,...
                'XData', [AddCrop(1) AddCrop(2)],...
                'YData', [AddCrop(3) AddCrop(4)]) ;
            
        %% Correct I1:
        C1= single( (I1-B1-Lambda2.*(I2-B2))./...
                    (B1-D1-Lambda2.*(B2-D2)) );           
        %% Correct I2 (Leakage)
        C2= single( (I2-B2-Lambda1.*(I1-B1))./...
                    (B2-D2-Lambda1.*(B1-D1)) );           
            
        %Save Processed Images
        b1=1;b2=1;
        save([Direct 'ProcImgs/Proc' sprintf('%05d', i)],'-v7.3','C1','C2','b1','b2');%,'C1C2');    
            
end
 
    