function [I1,I2] = TransCropImg(Name1, Name2, TFORM1, TFORM2, AddCrop)
%% Transforms a single image pair denoted by Name1 and Name2 using the tforms
%  TFORM1 and TFORM2 (which were found using PreRun).  Cs denotes the
%  corners of the grid, and AddCrop is a vector that crops the image

        % Load and Transform Image 1
        I1=imtransform( (imread(Name1) ),... %-B2) ,...
                TFORM1,...
                'nearest',...
                'FillValues', 0,...
                'XData', [AddCrop(1) AddCrop(2)],...
                'YData', [AddCrop(3) AddCrop(4)]) ;
         
         % Load and Transform Image 1
         I2=imtransform( (imread(Name2) ),... %-B2) ,...
                TFORM2,...
                'nearest',...
                'FillValues', 0,...
                'XData', [AddCrop(1) AddCrop(2)],...
                'YData', [AddCrop(3) AddCrop(4)]) ;
            
end
 
    